const { NextResponse } = require('next/server');
const { Company, AuditLog } = require('@/models');
const { withApiAuth } = require('@/lib/apiGuard');
const { companySettingsSchema } = require('@/validations/schemas');
const crypto = require('crypto');

async function getHandler(request) {
  try {
    const user = request.user;
    const companyId = request.companyId;

    if (user.role === 'staff') {
      return NextResponse.json({ error: 'Forbidden: Staff cannot access company settings.' }, { status: 403 });
    }

    const company = await Company.findByPk(user.role === 'super_admin' ? request.nextUrl.searchParams.get('companyId') : companyId);
    if (!company) {
      return NextResponse.json({ error: 'Company not found.' }, { status: 404 });
    }

    return NextResponse.json({ company });
  } catch (error) {
    console.error('GET Company Settings Error:', error);
    return NextResponse.json({ error: 'Internal Server Error' }, { status: 500 });
  }
}

async function putHandler(request) {
  try {
    const user = request.user;
    const companyId = request.companyId;

    if (user.role === 'staff') {
      return NextResponse.json({ error: 'Forbidden: Staff cannot modify company settings.' }, { status: 403 });
    }

    const body = await request.json();

    const targetCompanyId = user.role === 'super_admin' ? body.company_id : companyId;
    if (!targetCompanyId) {
      return NextResponse.json({ error: 'Company ID is required.' }, { status: 400 });
    }

    const company = await Company.findByPk(targetCompanyId);
    if (!company) {
      return NextResponse.json({ error: 'Company not found.' }, { status: 404 });
    }

    // Validate body
    const validation = companySettingsSchema.safeParse(body);
    if (!validation.success) {
      const errorMsg = validation.error.errors.map(e => e.message).join(', ');
      return NextResponse.json({ error: errorMsg }, { status: 400 });
    }

    const { company_name, website, email, phone, logo } = validation.data;

    // Update fields
    await company.update({
      company_name,
      website: website || null,
      email: email || null,
      phone: phone || null,
      logo: logo || company.logo
    });

    // Write audit log
    const ip = request.headers.get('x-forwarded-for') || '127.0.0.1';
    await AuditLog.create({
      company_id: company.id,
      user_id: user.id,
      action: 'Company Settings Updated',
      module: 'Settings',
      description: `Company settings updated by ${user.name}.`,
      ip_address: ip
    });

    return NextResponse.json({
      success: true,
      message: 'Company settings updated successfully.',
      company
    });

  } catch (error) {
    console.error('PUT Company Settings Error:', error);
    return NextResponse.json({ error: 'Internal Server Error' }, { status: 500 });
  }
}

// Regenerate API Key endpoint
async function postHandler(request) {
  try {
    const user = request.user;
    const companyId = request.companyId;

    if (user.role === 'staff') {
      return NextResponse.json({ error: 'Forbidden: Staff cannot regenerate API keys.' }, { status: 403 });
    }

    const body = await request.json();
    const targetCompanyId = user.role === 'super_admin' ? body.company_id : companyId;

    const company = await Company.findByPk(targetCompanyId);
    if (!company) {
      return NextResponse.json({ error: 'Company not found.' }, { status: 404 });
    }

    // Generate random API key
    const newApiKey = `${company.company_name.toLowerCase().replace(/[^a-z0-9]/g, '')}_wp_key_${crypto.randomBytes(16).toString('hex')}`;
    
    await company.update({ api_key: newApiKey });

    // Write audit log
    const ip = request.headers.get('x-forwarded-for') || '127.0.0.1';
    await AuditLog.create({
      company_id: company.id,
      user_id: user.id,
      action: 'API Key Regenerated',
      module: 'Settings',
      description: `WordPress integration API key regenerated by ${user.name}.`,
      ip_address: ip
    });

    return NextResponse.json({
      success: true,
      message: 'WordPress API key regenerated successfully.',
      api_key: newApiKey
    });

  } catch (error) {
    console.error('POST Regenerate API Key Error:', error);
    return NextResponse.json({ error: 'Internal Server Error' }, { status: 500 });
  }
}

export const GET = withApiAuth(getHandler);
export const PUT = withApiAuth(putHandler);
export const POST = withApiAuth(postHandler);
